### ISSUE TITLE
Koa Generic Session says use "Koa-session" instead

### ISSUE THREAD

**Issue by cpres** [mjbondra/koa-session-mongoose#11]
When I try to implement koa-session-mongoose within koa-session it errors out:

`app.use(session(app, {store: new MongooseStore()}));`

```
app.use((0, _koaSession2.default)(app, { store: new _koaSessionMongoose2.default() }));
                                                ^

TypeError: _koaSessionMongoose2.default is not a constructor
```

I'm not sure if the issue resides on koa-session or this module, but your documentation isn't helping me figure out the best way to implement koa-session-mongoose on koa-session. Which is now the session module koajs is suggesting we use

**Comment by mjbondra** [comment]
Use the latest release (`koa-session-mongoose@^2.0.0`) for `koa-session` support. The code examples in the readme file should give you a pretty good idea of how to proceed.
