### ISSUE TITLE
Cookies not getting destroyed and TypeError

### ISSUE THREAD

**Issue by ayushsharma82** [mjbondra/koa-session-mongoose#12]
I am getting a type error -  Cannot destructure property `data` of 'undefined' or 'null'.
which is in "lib/index.js" Line 25

So this happens when there are 2 windows of same url are opened and we click logout on 1st window. 
The cookies are not getting deleted hence causing this error. 

When i Delete all the Cookies the Webpage Starts working fine again. 
(Cookie Deletion by EditThisCookie Chrome Plugin)

According to my knowledge the cookies which are left are making backend to seach for this 'sid' again in database and it returns a null value because it couldn't find it. Need a Solution please.

**Comment by ayushsharma82** [comment]
Update: It got Fixed. i don't how but restarting the node app made it ok. Weird. I will close it until i get the error again.

**Comment by mjbondra** [comment]
I just released a new version (`v2.0.2`) that addresses the `TypeError` that occurs when a session is not found:
https://github.com/mjbondra/koa-session-mongoose/blob/53d0c945459e2fd6cf6d950c6e5c38111ade7184/lib/index.js#L25

**Comment by ayushsharma82** [comment]
Great Thanks.
