### ISSUE TITLE
Allow "Schema" constructor to be used from injected connection

### ISSUE THREAD

**Issue by rfink** [mjbondra/koa-session-mongoose#6]
I've had a few issues where, if there is a version mismatch between the root mongoose and the module's version of mongoose, passing in a connection will cause an issue.  P.R. incoming that optionally uses the Schema constructor from the passed in mongoose instance.

**Comment by mjbondra** [comment]
Thanks for the PR.

**Comment by rfink** [comment]
Anytime.
