### ISSUE TITLE
delete mongodb session

### ISSUE THREAD

**Issue by sanrudongfeng** [mjbondra/koa-session-mongoose#9]
'koa-session-mongoose'  seems like ok.but when I delete mongodb 'sessions' collections, why the sesssion has been exist,even restart program?????

**Comment by mjbondra** [comment]
This is probably a problem with the session library that you are using. Once you delete the collection that contains the session documents, the data no longer exists -- this library doesn't store data in memory or anything other than MongoDB. Try using the latest release `koa-session-mongoose@^2.0.0`.
